@host = http://localhost:5215

POST {{host}}/api/v1/films
Content-Type: application/json

{
  "title": "Inception",
  "synopsis": "Um ladrão invade sonhos.",
  "genre": "FiccaoCientifica",
  "releaseDate": "2010-07-16T00:00:00Z",
  "durationMinutes": 148,
  "rating": 8.8,
  "isActive": true
}

###
GET {{host}}/api/v1/films?active=true&page=1&pageSize=10
